### ISSUE TITLE
Hotbarplus issue

### ISSUE THREAD

**Issue by kongg2** [cmooref17/ReservedItemSlotMods#14]
Hello mod maker, I think i found a problem. I set the default inventory to 5 slots in config, and when i press no 5 on my keyboard, it swap to the reservedslot for a brief moment and then back to slot no 1. Its like im pressing left alt for a moment. Thanks.

**Comment by kongg2** [comment]
Hello again, after the latest update, the problem still persist. thanks

**Comment by cmooref17** [comment]
Could you check if it's still happening? I think this has been fixed now.

**Comment by kongg2** [comment]
> Could you check if it's still happening? I think this has been fixed now.

Yes, it works perfectly now. Thanks!!
