### ISSUE TITLE
HotBarPlus Problem

### ISSUE THREAD

**Issue by BBAPepsiMan** [cmooref17/ReservedItemSlotMods#16]
Heyyyyy, got a compatibility problem with your HotbarPlus mod. As soon as I grab an item for a reserved slot, all but 4 of my regular slots are sucked in to overlap with the bottom right corner of the reserved slots. All items for reservation are also piled on top of each other. The normal slots are inaccessible.

**ReservedItemSlotCore settings:**

ForceEnableThisModIfNotEnabledOnHost: false

DisplayNegativePrioritySlotsLeftSideOfScreen: true

FocusReservedItemSlotsHotkey: <Keyboard>/leftAlt

ToggleFocusReservedHotbar: false

PreventReservedHotbarSlotFade: false

EnablePurchasingItemSlots: false

GlobalItemSlotPriceModifier: 1

**HotbarPlus settings:**

UseHotbarNumberHotkeys: false

InvertHotbarScrollDirection: true

OverrideHotbarHudSpacing: 4

OverrideFadeHudAlpha: 0.13

OverrideHotbarHudSize: 1

UseItemQuickDropConfig: false

UseDefaultItemSwapInterval: false

UseDefaultItemDropInterval: false

UseDefaultItemActivateInterval: true

HotbarSize: 10

**Comment by cmooref17** [comment]
If you could verify for me if this has been fixed in the latest version or not, that would be  great! If so, let's close this issue.

**Comment by BBAPepsiMan** [comment]
After testing last night, the error appears to be fixed. Thanks!
