### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by 1753449579** [cmooref17/ReservedItemSlotMods#18]
I used the old version to make it work，the latest version may have bug I think

**Comment by 1753449579** [comment]
I found the mod in conflict with this mod，my translation mod(https://thunderstore.io/c/lethal-company/p/SweetFox/Lethal_Company_Simplified_Chinese_Localization/)。
I don't know why

**Comment by cmooref17** [comment]
Ah, what was the issue exactly?

**Comment by cmooref17** [comment]
By the way, if it helps, you can add the translated item names to the config which may add the items into the slots if they're named differently. Not 100% sure, though.

**Comment by Xyc1596** [comment]
> By the way, if it helps, you can add the translated item names to the config which may add the items into the slots if they're named differently. Not 100% sure, though.

It works!
I have the same problem after updating this mod to the latest version (2.0.6) and solved it by simply adding the translated names to the config.
I think this method can be published as a temporary solution before the conflict is truly solved.
