### ISSUE TITLE
Lethal Config broken

### ISSUE THREAD

**Issue by DeathWrench** [cmooref17/ReservedItemSlotMods#19]
# With versions before 2.0.0:
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/45341450/5a1c9574-5a4d-4fb4-bc85-d143523169b8)
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/45341450/17f03672-4537-49d1-9db7-8b317fee1b79)
# After updating all mods:
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/45341450/255f25c7-79b7-4ec8-b5e1-131d52b6671c)
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/45341450/53201b5a-bd38-445d-9dd8-28fe0315415b)

**Comment by cmooref17** [comment]
Does it show the config files exist? Like can you see them in r2modman? I don't know why they don't show up in game for you. It's working for me just fine.

**Comment by cmooref17** [comment]
Ah, it's likely because they haven't updated their mod to support the new core version/api. I have already let them know about this and hopefully they will update them soon.

**Comment by DeathWrench** [comment]
I hope you don't mind, for now I've made a link to easily downgrade with mod managers: https://deathwrench.github.io/ReservedSlotsModsDowngrader/
It's the same as clicking these buttons (just less tedious):
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/45341450/3fd744a5-a8cd-4863-9698-75aec8c4de68)

**Comment by cmooref17** [comment]
Yeah, that's fine. Players could roll back, or they could disable the reserved item slot mods that haven't updated with the latest core yet. I'm assuming you didn't make that just for yourself haha, are you sharing this with people to help them roll back?

**Comment by DeathWrench** [comment]
> Yeah, that's fine. Players could roll back, or they could disable the reserved item slot mods that haven't updated with the latest core yet. I'm assuming you didn't make that just for yourself haha, are you sharing this with people to help them roll back?

Yeah lol, to help a friend and I rollback, and because markdown doesn't support links that don't start with https, I couldn't post in discord the install button links.

**Comment by DeathWrench** [comment]
Recent Lethal Config update fixed this problem. Additionally I updated the Reserved mods that didn't work with the new core:
- [ReservedBoomboxSlot](https://thunderstore.io/c/lethal-company/p/DeathWrench/ReservedBoomboxSlot/)
- [ReservedKeySlot](https://thunderstore.io/c/lethal-company/p/DeathWrench/ReservedKeySlot/)
- [ReservedTZPSlot](https://thunderstore.io/c/lethal-company/p/DeathWrench/ReservedTZPSlot/)
