### ISSUE TITLE
Host Not Able to Use Key Bindings for Reserved Slots

### ISSUE THREAD

**Issue by PerryW11** [cmooref17/ReservedItemSlotMods#2]
When I host a game, I've noticed the keybinds to interact with the items on the reserved slots don't work. I can't hold x to chat, and the f key doesn't toggle the flashlight like it used to. I double checked to ensure it wasn't a key binding issue. The other person playing with me is able to use it just fine though. Not sure if there's a coincidence in that or not. 

Great mod btw

**Comment by cmooref17** [comment]
I will be looking into this ASAP, thank you!

**Comment by cmooref17** [comment]
Could you let me know if these issues are still around in 2.0.6? Thanks! I think I have fixed them all! (or most of them)

**Comment by PerryW11** [comment]
Looks good for this issue. Thanks!
