### ISSUE TITLE
Can't switch to reserved slot items if emoting

### ISSUE THREAD

**Issue by PerryW11** [cmooref17/ReservedItemSlotMods#20]
I guess this isn't much of an issue if you *aren't* using "AllwaysCanDance" since you can just move to stop the emote, but if you are using this, basically you have to wait for the entire emote to finish before you can switch to reserved slot items. 

I'm assuming you can just set some condition to ensure you can switch to the reserved slots even if you're emoting. This could be more of an issue with the other mentioned mod though.

**Comment by cmooref17** [comment]
I specifically disallow it, but you do bring a good point about moving while emoting. I could probably add an exception to this if this is enabled, but do note that some mods, such as my reserved item slot mods, and hotbar plus might not let you swap items with their restrictions.

**Comment by cmooref17** [comment]
Sorry, I replied to this thinking you posted this on my TooManyEmotes github. I'll think of a solution for this, though.

**Comment by DeathWrench** [comment]
Allways Can Dance is old, this is a better implementation: https://thunderstore.io/c/lethal-company/p/boring/EmoteWhileInMotion/

**Comment by cmooref17** [comment]
This can be allowed in my config, which I thought you were referring to. I'm not sure how other mods' implementations for this work with mine.

I also can't confirm mine is foolproof since I don't emote while moving, so I only tested it for a little bit when I added it.

**Comment by cmooref17** [comment]
Wait, again. I thought we were talking about TooManyEmotes... I'm tired. I'm going to bed lol

**Comment by cmooref17** [comment]
I will change this restriction so it only prevents emoting if you're emoting from my TooManyEmotes mod. It will probably cause less problems for others.

**Comment by cangming99** [comment]
In versions prior to ReservedItemSlotCore 2.0, it was possible to switch to reserved slot items while moving and emoting, and there were no mod conflicts. 
Moreover, with the recent update of HotbarPlus a few days ago, swapping item slots with the number keys while using emotes has also been prohibited. I think I now only have two options: either give up maintaining emotes while moving or stay with the old version. 
Regardless, both mods are great works.

**Comment by cmooref17** [comment]
Yes, similar to what I just said with the reserved item slots, hotbar plus will get the same treatment. Preventing item swaps will only be for when the player is emoting with too many emotes. This will be added tomorrow

**Comment by cmooref17** [comment]
To be honest, the thought never crossed my mind about moving while emoting, so I can definitely see now why this would conflict lol

**Comment by cangming99** [comment]
Using emotes while moving brings a lot of fun. Get some rest early, good night.

**Comment by PerryW11** [comment]
I totally blanked on responding and came across this issue. Obviously fixed now - will close. Thanks!
