### ISSUE TITLE
Item Desync

### ISSUE THREAD

**Issue by test512b** [cmooref17/ReservedItemSlotMods#22]
Happens randomly whenever someone picks up an item from the ground. The item stays on the ground (But not for the one who picks it up) and no one else can interact with it. The item will then teleport to where the person who grabbed it drops it.
It will also set your weight to 0 (when using the Back Muscles upgrade from LateGame Upgrades) when you try to interact with the desynced item.

ReservedItemSlotCore v2.0.9

**Comment by cmooref17** [comment]
Does this happen all the time? Even at the start of the game?
Not saying this is the cause, but do you have purchasing slots enabled or not? Might be helpful when looking into this, but it could also be a conflict with another mod. I personally haven't seen this since 2.0.5.

**Comment by NakiriFox** [comment]
I don't think this issue is caused by ReservedIdemSlotCore
