### ISSUE TITLE
Can't Picking Up Items While Weapon Slot is Active

### ISSUE THREAD

**Issue by cangming99** [cmooref17/ReservedItemSlotMods#26]
When I press the ‘T’ key to take out a weapon from the Weapon Slot, I can’t pick up other items on the ground. I can only pick them up when I switch back to the main hotbar.

**Comment by cangming99** [comment]
Yeah, completely fixed in 2.0.13

**Comment by cmooref17** [comment]
Okay, glad to hear! (sorry, I guess I never responded to this one)
