### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by cangming99** [cmooref17/ReservedItemSlotMods#3]
When I press the 'T' key, if I switch back to the main hotbar not through the mouse wheel but through a keypress (I have installed the HotbarPlus mod), then I can no longer switch back to the dedicated inventory slots using 'Alt' or 'T'.

Both of these mods are ones I really like, and it’s hard to give up one of them. For now, I can only disable ReservedWeaponSlot. In fact, if I hold down ‘Alt’ and switch back to the main hotbar through a shortcut key, the same problem occurs, but generally, I wouldn’t operate this way. I would release the ‘Alt’ key to return to the main hotbar. It’s only when using the ‘T’ key that this bug is more likely to be triggered.

**Comment by cmooref17** [comment]
You could disable the T keybind temporarily in the keybind menu if you are using inpututils, at least until I can figure out what's going on. I was using both mods, and I don't remember running into any issues. I will double check, thanks!

**Comment by cangming99** [comment]
I recorded two videos, one triggered by using the ‘T’ key and the other by using the ‘Alt’ key, and you can see that when I use items from the dedicated inventory slots, if I switch back to the main hotbar using the hotkey, I can no longer take out the items I placed in the dedicated inventory slots.

https://github.com/cmooref17/ReservedItemSlotMods/assets/85931842/d1fe39c2-a393-43ca-942d-c0b1916c13a7

https://github.com/cmooref17/ReservedItemSlotMods/assets/85931842/384ba2e9-65eb-4fbb-bd80-a842b4cd29ff

**Comment by cangming99** [comment]
I recorded two videos, one triggered by using the ‘T’ key and the other by using the ‘Alt’ key, and you can see that when I use items from the dedicated inventory slots, if I switch back to the main hotbar using the hotkey, I can no longer take out the items I placed in the dedicated inventory slots.

https://github.com/cmooref17/ReservedItemSlotMods/assets/85931842/77d23cc5-7cea-4784-b493-28288ca7adfc


https://github.com/cmooref17/ReservedItemSlotMods/assets/85931842/627f525f-cb24-4bf5-9d1d-bc9788535b09

**Comment by cmooref17** [comment]
I don't know if I fixed this exactly, but this could have been fixed as a side effect to the other major bugs I fixed. Could you let me know if this is still an issue? Thanks!

**Comment by cangming99** [comment]
Um…, I think I might have found the reason. When I press the number key 1, it uses some emotes, and during this time, I can’t use the dedicated inventory slots. It only works when I stop the emote. Interestingly, I used a mod called ‘InfiniteEmote,’ which allows me to keep using emotes indefinitely. This resulted in not being able to take out items until I stop the action. There was no problem before version 2.0, and I’m not sure if this is a bug now because if I don’t use InfiniteEmote, after the character moves and interrupts the dance, it returns to normal.Thank you for your answers all this time.

**Comment by cangming99** [comment]
I tested the ReservedItemSlotCore at v1.8.17, where I could press the ‘Alt’ key to take out the items I placed in the dedicated inventory slots while dancing. However, this function no longer works after upgrading to version 2.0 or later.

**Comment by cangming99** [comment]
Resolved in version 2.0.12
