### ISSUE TITLE
hellp

### ISSUE THREAD

**Issue by JangoKeeng** [cmooref17/ReservedItemSlotMods#33]
Здравствуйте, как поменять клавишу активайции в конфигурации?  мод(too many emotes)

**Comment by JangoKeeng** [comment]
> Здравствуйте, как поменять клавишу активайции в конфигурации? мод(слишком много эмоций)

игра Leethal company

**Comment by cmooref17** [comment]
First off, you posted this on the wrong github. This github is for reserved item slots.

And second, to answer your question, you will need to install the InputUtils mod by Rune580, and then you will be able to change the keybindings in the menu.

**Comment by JangoKeeng** [comment]
thank 
you
