### ISSUE TITLE
client side no longer works

### ISSUE THREAD

**Issue by ChefShenko** [cmooref17/ReservedItemSlotMods#35]
i tried change true both lethal config and normal config file but it doesnt work. Its only working when i am the host

**Comment by ChefShenko** [comment]
Pls answer it

**Comment by cmooref17** [comment]
Sorry, but you didn't even tell me what's wrong. It sounds like you're trying to set a config option to true, but it's not working? What config option isn't working?

Or does the whole mod not work when you're not the host?

**Comment by ChefShenko** [comment]
Like i said its working when i am the host but when i joined public lobby its not
And i enabled true both config file and lethal config then i restarted but it still not working

**Comment by cmooref17** [comment]
Sorry, I thought this was the TooManyEmotes github. I understand what you're saying. Yes, I've been told that this is currently not working. I will be trying to look into this as soon as I can.

**Comment by ChefShenko** [comment]
Thanks and Which version do you recommend?

**Comment by cmooref17** [comment]
If you're wanting to use this mod with other people who do not have it, then I believe the latest version before 2.0.0 (I can't remember the last 1.x.x version right now) would be your best bet, at least until I can fix this soon.

**Comment by ChefShenko** [comment]
You are number 1
