### ISSUE TITLE
[Bug] Items in the hotbar and the reserved hotbar at the same time

### ISSUE THREAD

**Issue by TsamT** [cmooref17/ReservedItemSlotMods#36]
hi i want report a bug that i found 
the bug appears when i leave and rejoin the game making the items bugs here is a screenshot about the bug and i hope you fix it
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/153838356/ac32d825-68b8-45e1-8d74-b504e937b8a2)

**Comment by cmooref17** [comment]
I've seen similar things like this in the past, but there were also errors in my console when this happened. Do you know if any errors showed up when this happened? And does this always happen, or did it start happening in the middle of the game?

**Comment by TsamT** [comment]
@cmooref17 the bug always can appear when i leave the game when not orbiting it cause the bug, but if have the shovel. it bugs when leave the game when orbiting or not. another bugs i found when grabbing items, appears 2 instead of 1, but dropping the item the duplicated item still present in the hotbar but won't be visible when holding it and can't be dropped or used, when grab the flashlight, key and/or shovel and you drop an item, you can't interact the hotbar and anything, that's all that i found

**Comment by cmooref17** [comment]
Sorry for the late response. Do you enable purchasing the item slots or no?
And just checking again, do you remember seeing any errors in the console when this happened?
If you could share them, that would be very helpful. I haven't gotten this error to show up since I tried your steps.

**Comment by TsamT** [comment]
i dont have that option on and i see this error and i discover that a mod that i have called "quality company"  makes the bug here are the logs of the console:[Error  : Unity Log] NullReferenceException
Stack trace:
QualityCompany.Modules.Inventory.ScrapValueModule.UpdateTotalScrapValue () (at <022eacd116e64c25b33040d28bcbb18c>:IL_009A)
QualityCompany.Modules.Inventory.ScrapValueModule.OnUpdate (GrabbableObject currentHeldItem, System.Int32 currentItemSlotIndex) (at <022eacd116e64c25b33040d28bcbb18c>:IL_0000)
QualityCompany.Modules.Inventory.InventoryBaseUI.ForceUpdateAllSlots (GameNetcodeStuff.PlayerControllerB instance) (at <022eacd116e64c25b33040d28bcbb18c>:IL_0017)
QualityCompany.Modules.Inventory.InventoryBaseUI.OnUpdate (GameNetcodeStuff.PlayerControllerB instance) (at <022eacd116e64c25b33040d28bcbb18c>:IL_001A)
QualityCompany.Events.GameEvents.OnPlayerGrabObjectClientRpc (GameNetcodeStuff.PlayerControllerB instance, GrabbableObject go) (at <022eacd116e64c25b33040d28bcbb18c>:IL_0018)
QualityCompany.Patch.PlayerControllerBPatch.RefreshLootOnPickupClient (GameNetcodeStuff.PlayerControllerB __instance, Unity.Netcode.NetworkObjectReference& grabbedObject) (at <022eacd116e64c25b33040d28bcbb18c>:IL_0018)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB.GrabObjectServerRpc (Unity.Netcode.NetworkObjectReference grabbedObject) (at <09f109276c764f589f47f312aab5547a>:IL_018C)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_1554282707 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <09f109276c764f589f47f312aab5547a>:IL_0096)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::BeginGrabObject>(PlayerControllerB)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::Interact_performed>(PlayerControllerB, CallbackContext)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

**Comment by TsamT** [comment]
so maybe removing the mod it solve the problem

**Comment by cmooref17** [comment]
Do you know if you had any custom configs set for qualitycompany? Or were they all default? I loaded up a game with quality company, but I couldn't seem to reproduce this, even with a second client.

**Comment by TsamT** [comment]
I saw that the bug occurs without your mods, so the bug is not in your mods
