### ISSUE TITLE
Unknown type bug issue

### ISSUE THREAD

**Issue by vasvasilyev** [cmooref17/ReservedItemSlotMods#39]
Hello. A couple days ago I was playing LC with my teammate for 3 hours. Somewhere around 1.5 hours when I have remade the lobby, my teammate couldn't wear or see any skin and the ship interior for him changed to default one. After several attempts of remaking the lobby he made skins work and the ship became usual for him but he lost reserved slots. After another reconnect everything returned back to when the bug appeared. I tried to make him host and I encountered the same bug as him.
Next day I was trying to find the buggy mod and this bug resolved only after disabling reserved slots entirely.

So the bug is - after 3 launches the ship becomes default nad skins break, sometimes even models become invisible. Occasionally slots may disappear and the bug disappears.

Reserved slots are up-to-date, game files verified etc.

**Comment by vasvasilyev** [comment]
Also someone suggested to reset game data entirely, that worked also only for 3 games, then it breaks.

**Comment by cmooref17** [comment]
That is very interesting. My mod doesn't even touch any of that.
My guess is that maybe my mod ran into an error, which stopped the execution of some of the vanilla code because the error wasn't caught and handled correctly.

Would you happen to know if there were any errors in the console/logs that the reserved mods might have caused?

**Comment by cmooref17** [comment]
Also, were you guys playing with the slots automatically unlocked, or did you enabling purchasing them?

**Comment by vasvasilyev** [comment]
Yes, I did open them in config

**Comment by vasvasilyev** [comment]
Idk why i didn't see that first message, so about errors. First thing when I tried to find out why - I tried to search for those errors. I said my friend to show me console, but the logs were normal, there were some errors, but they are kind of usual already. I also watched my logs when I was client, and nothing.

**Comment by vasvasilyev** [comment]
I will try to reproduce situation again, maybe I have skipped it.

**Comment by vasvasilyev** [comment]
At first I wasn't totally sure about that the issue in reserved slots, but yesterday evening I was playing LC for several hours and haven't met this bug anymore. I have reverted mod version to 2.0.7 I think. In 2.0.7 things are good.

**Comment by vasvasilyev** [comment]
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/78742698/6930d8b3-7ffe-4ab0-adc8-84958ac9762d)
So I have updated reserved mods again to latest and met this bug.
Ship is totally empty (shouldn't), bunk beds present (also shouldn't), interior is default, skins missing.
I have LogOutput file
[LogOutput.log](https://github.com/cmooref17/ReservedItemSlotMods/files/15041235/LogOutput.log)
But I don't see anything strange, only MoreEmotes seems to encounter some problems, but they are kind of regular for me already. And old version of slots works normal.

**Comment by vasvasilyev** [comment]
Hello @cmooref17 I have't received an answer for a week now... Looking for your answer.

**Comment by cmooref17** [comment]
Oh sorry. I must have missed your message where you included the log file. Let me take a look at this in a little bit and hopefully I can see what might be going on.

**Comment by cmooref17** [comment]
Also, did you mention if you were playing on v49 or v50? I see errors caused by more emotes because it might be referencing an old method? And it hasn't been updated to support v50, at least not fully. Maybe this isn't even causing issues, but I'll keep looking through the logs.

**Comment by cmooref17** [comment]
Okay, I'm guessing more emotes is fine. I don't think those errors would prevent any vanilla code, or code from other mods from running.

Have you tried this since the last ReservedItemSlotCore update by chance? I was made aware of a bug where if a player is holding a reserved item before a player joins, that player wouldn't receive any synced updates about unlockables, and potentially other updates, like maybe skins like you were referring to? I'm not sure about the skins part. This bug was fixed since then, but I guess I'm just wondering if that sounds like it might have been your issue. Thanks and let me know!

**Comment by vasvasilyev** [comment]
About latest reserved, not yet. I may try it later. I am playing on v50 stable

**Comment by vasvasilyev** [comment]
Sooo we tried to update reserved slots to the laaatest version you recommended and seems like it works. I guess bug was fixed..?

**Comment by vasvasilyev** [comment]
I will try to play it now on our modpack and I will let you know (we have checked mods on test modpack)

**Comment by cmooref17** [comment]
Okay thank you, I appreciate it!

**Comment by vasvasilyev** [comment]
I think it works fine, although the mod broke for single time, but after restart it got back to normal.

**Comment by vasvasilyev** [comment]
Hello @cmooref17 so after 2 days of playing when I pick up reserved items before the client connects, it won't show reserved slots now. Maybe the bug isn't fully fixed.

**Comment by cmooref17** [comment]
Sorry, let me look into this in a bit to see if I can figure out what exactly is going on.
And just double checking, did you say you enabled purchasing the reserved item slots in the config? Or do you not have this option set?

**Comment by vasvasilyev** [comment]
I have unlocked it thru config. My friend loses his reserved items kinda randomly, because sometimes I pick reserved items and he is fine, but sometimes I pick and it breaks.

**Comment by vasvasilyev** [comment]
Oh, gosh, I totally forgot the word "sometimes" when I was writing that message. My bad >_<
It's not permanent, it occurs a bit rarely and fixes with plain restart of the game.
