### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by JayIini** [cmooref17/ReservedItemSlotMods#4]
Hey, it says that the slot will be available again as soon as I start but thats not the case. So i basicly cant use the mod at all and I really miss them. c:

**Comment by cmooref17** [comment]
Have you purchased the slots at the terminal? I think I fixed the issue with the terminal not giving tips on how to purchase them.

**Comment by JayIini** [comment]
Ohhh no I haven´t. Thank you very much!

**Comment by cmooref17** [comment]
Coul
