### ISSUE TITLE
Compatibility with Touchscreen mod

### ISSUE THREAD

**Issue by DumbCodeGenerator** [cmooref17/ReservedItemSlotMods#40]
Hello. I use the [Touchscreen mod](https://github.com/TheDeadSnake/LC-Touchscreen). After one of the latest updates, the walkie doesn't activate, when I am looking at the radar

I believe, it's because of version 2.0.3 with multiple checks, when you can activate the walkie

**Comment by cmooref17** [comment]
Does looking at the monitor put you in an animation, or lock you to the screen?
I might have a check that prevents using the walkie if you're in a special animation. I'm not 100% sure. I'll have to check later.

**Comment by cmooref17** [comment]
The mod sets it so you're in a "grabbing object animation" when looking at the monitor for some reason, so I just removed this restriction. It should be fixed now in the latest update
