### ISSUE TITLE
[HotbarPlus Suggestion] Custom configurable swap delay instead of a boolean

### ISSUE THREAD

**Issue by zndrmn** [cmooref17/ReservedItemSlotMods#41]
I just want to say that I'm sorry for sending this here, I know this isn't the right repo. 
I didn't know where to go to suggest this feature since there's no obvious way to contact you, and there's also no repo for HotbarPlus.

Basically, right now you can either have a ton of delay or no delay at all. 
I think it would be great if you could make it so that we can set the delay ourselves.

Oh and it would be nice if you could have an option for number keys/hot keys to not be affected by the delays

Again, sorry for sending this report here.

**Comment by cmooref17** [comment]
Nah, it's all good! When I have some free time, maybe this weekend, I'll look into this!

**Comment by zndrmn** [comment]
Moved report to https://github.com/cmooref17/Lethal-Company-HotbarPlus/issues/1
