### ISSUE TITLE
ObjectVolumeController Bug

### ISSUE THREAD

**Issue by Teals53** [cmooref17/ReservedItemSlotMods#42]
When i go back to the main menu it gives this error and i open this issue here cuz there is no repo for this plugin

[Error  : Unity Log] NullReferenceException
Stack trace:
ObjectVolumeController.Patcher.ChangeVolumePatcher.GetObjectLookingAt (GameNetcodeStuff.PlayerControllerB __instance) (at <8dc42536a4c7475399fbb83fa911d052>:IL_0063)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)

**Comment by cmooref17** [comment]
Btw, this mod might get restructured very soon, and hopefully this bug goes away with it. I'll let you know when the update is pushed!
