### ISSUE TITLE
Picking up laser pointer breaks controls in 2.0.4

### ISSUE THREAD

**Issue by jikued** [cmooref17/ReservedItemSlotMods#45]
Since the update to 2.0.4 I have been having an issue where my controls break when I pick up a laser pointer with my flashlight. I am not running too many mods but here is my current list in order: 
BepinEx, Lethal InputUtils, ShipLoot, ReservedItem Core, MoreCompany, Latecompany, ReservedFlashlight, Reserved Walkie, TooManyEmotes, MoreSuits, OpenBodyCams, and Bocchi_Cosmetics. I am not sure if any of these mods cause the issue.

To explain a bit more clearly, with a flashlight toggled on inside of your inventory picking up a turned off laser pointer (didn't test turned on) your controls will break. I had success in fixing them when pressing alt, however the pro-flashlight and laser pointer were overlapping in my hand for a moment. I have also not tested this with multiple pro flashlights, or regular flashlights.

**Comment by cmooref17** [comment]
Hmm, that's strange. Would you happen to have any errors in your console/log when your controls break? If so, and you could share them, it would help out a ton!

**Comment by jikued** [comment]
I didn't see any when it happened the first time, but I failed to check the other time. I can hop back in and test for you a bit later though, and send over the logs.

**Comment by jikued** [comment]
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/169414073/ef7961e8-2869-41fa-b8c8-7b410574e4b6)

It seems my grab was invalidated. I should add that I turned on Imperium for testing, at the bottom of my list. For this instance pressing alt didn't fix the issue. I don't know if/where bepinex posts a full dump, so if you would like me to hop back in to test again I can do that for you.

**Comment by cmooref17** [comment]
Usually the error would be right above all of those spamming lines. I've seem errors like that before. That's the part that would be helpful!

**Comment by jikued** [comment]
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/169414073/ac7a15d6-2c02-43bd-af1f-06ca35e23978)
![image](https://github.com/cmooref17/ReservedItemSlotMods/assets/169414073/776c3e50-1d2b-4990-a3dc-c1a9d0cb7909)



My bad on that one! found the error, let me know if you want me to recreate it again and show you more of the log. Another thing that happened is that it seemed like a second item appeared in my inventory as well. You can see it has scrolled my selected item to the second slot despite me picking up the laser pointer in the first slot. Also scan and movement work, it is an issue with essentially every other control.

**Comment by cmooref17** [comment]
Okay, thanks! I'll take a look as this as soon as I can!

**Comment by jikued** [comment]
Following the same
