### ISSUE TITLE
mod does not work

### ISSUE THREAD

**Issue by ShadowFightZ2** [cmooref17/ReservedItemSlotMods#5]
hello mod maker i just made a account to let you know that you mod reserved item flashlight walkie and weapons mod is not working any more after the update a day ago i hope you will be able to fix it cuss you mod is really handy

**Comment by cmooref17** [comment]
I have heard of some issues, but I will have to look at them when I get home. Could you clarify what the issues are? Are you enabling purchasing slots, or not? Are you the host? Thanks!

**Comment by ShadowFightZ2** [comment]
It was working now i just didnt see that you needed to purches them on the
terminal i am sorry

Op wo 13 mrt. 2024 17:09 schreef cmooref17 ***@***.***>:
