### ISSUE TITLE
the mod doesn't work

### ISSUE THREAD

**Issue by Gulyashenko** [cmooref17/ReservedItemSlotMods#8]
Hi, I installed a mod for an additional flashlight slot, but for some reason the slot did not appear, although the ability to purchase the slot was disabled. What could be the problem? In the flashlight mod, the slot does not appear at all, and in the walkie-talkie mod it simply does not work
![изображение_2024-03-13_230738509](https://github.com/cmooref17/ReservedItemSlotMods/assets/99470525/5b922cc4-2e08-402f-a9e4-1ea4ae63b5f5)

**Comment by Bloody1soldier** [comment]
I'm having the same problem and I use  thunderstore and for the config it just says override
